/* Vcg plugin internal common routines.

   Copyright (C) 2009, 2010, 2011 Mingjie Xing, mingjie.xing@gmail.com. 

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>. */

#include "vcg-plugin.h"

/* Used as a string buffer.  */
static struct obstack str_obstack;

/* Print error messages.  */

static void
vcg_error (const char *format, ...)
{
  va_list ap;

  va_start (ap, format);
  fprintf (stderr, "%s: error: ", vcg_plugin_common.plugin_name);
  vfprintf (stderr,  format, ap);
  va_end (ap);
  fputc ('\n', stderr);
}

/* Dump the top graph into file FNAME.  */

static void
vcg_dump (char *fname)
{
  FILE *fp;

  if ((fp = fopen (fname, "w")) == NULL)
    {
      vcg_plugin_common.error ("failed to open file %s.", fname);
      return;
    }

  /* Put the version information on top.  */
  fprintf (fp, "// Generated by GCC VCG Plugin %s\n" \
               "// Report bugs to <mingjie.xing@gmail.com>\n" \
               "// Home page: http://code.google.com/p/gcc-vcg-plugin\n" \
               "// %s", vcg_plugin_common.version, vcg_plugin_common.info);

  gdl_dump_graph (fp, vcg_plugin_common.top_graph);
  fclose (fp);
}

/* Show the top graph.  */

static void
vcg_show (char *fname)
{
  char *cmd;
  pid_t pid;

  cmd = concat (vcg_plugin_common.vcg_viewer, " ", fname, NULL);
  pid = fork ();
  if (pid == 0)
    {
      system (cmd);
      exit (0);
    }
  free (cmd);
}

/* Do the common initialization work for each view/dump command.  */

static void
vcg_init (void)
{
  gdl_graph *graph;

  /* Create the top graph.  */
  graph = gdl_new_graph ("top graph");
  gdl_set_graph_node_borderwidth (graph, 1);
  gdl_set_graph_edge_thickness (graph, 1);
  gdl_set_graph_splines (graph, "yes");
  gdl_set_graph_colorentry (graph, 100, 70, 130, 180);
  gdl_set_graph_node_textcolor (graph, "white");
  gdl_set_graph_node_color (graph, "100");
  gdl_set_graph_edge_color (graph, "100");
  vcg_plugin_common.top_graph = graph;

  /* Initialize the string obstack.  */
  obstack_init (&str_obstack);

  /* Open the temp stream.  */
  vcg_plugin_common.stream = open_memstream (&vcg_plugin_common.stream_buf,
                                             &vcg_plugin_common.stream_buf_size);
}

/* Do the common cleanup work for each view/dump command.  */

static void
vcg_finish (void)
{
  gdl_free_graph (vcg_plugin_common.top_graph);
  obstack_free (&str_obstack, NULL);
  fclose (vcg_plugin_common.stream);
  free (vcg_plugin_common.stream_buf);
}

/* Print into the string buffer.  */

static void
vcg_buf_print (char *fmt, ...)
{
  va_list ap;

  va_start (ap, fmt);
  obstack_vprintf (&str_obstack, fmt, ap);
  va_end (ap);
}

/* Finish a string and return the address.  */

static char *
vcg_buf_finish (void)
{
  obstack_1grow (&str_obstack, '\0');
  return obstack_finish (&str_obstack);
}

vcg_plugin_common_t vcg_plugin_common =
{
  "VCG Plugin",
  "1.5",
  NULL,
  "vcgview",
  NULL,
  "dump-temp.vcg",
  NULL,
  NULL,
  0,
  vcg_init,
  vcg_finish,
  vcg_error,
  vcg_dump,
  vcg_show,
  vcg_buf_print,
  vcg_buf_finish
};
